name: Build usbpcap for Windows on ARM(64)

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: windows-11-arm
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: true
      - name: Apply patches
        run: |
          for patch in ./Code\ Patches/*.patch; do
            patch -p0 <"$patch"
          done
