name: Build usbpcap for Windows on ARM(64)

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: windows-11-arm
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
        with:
          submodules: true
      - name: Apply patches
        shell: pwsh
        run: |
          Get-ChildItem -Path 'Code Patches' -Filter '*.patch' | ForEach-Object {
            git apply $_.FullName
          }
