name: Build usbpcap for Windows on ARM(64)

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: windows-11-arm
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: true
      - name: Apply patches
        shell: pwsh
        run: |
          # Use PowerShell to find and apply all .patch files in the "Code Patches" directory
          Get-ChildItem -Path 'Code Patches' -Filter '*.patch' | ForEach-Object {
            patch -p0 < $_.FullName
          }
