name: Build usbpcap for Windows on ARM(64)

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: windows-11-arm
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
        with:
          submodules: true

      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v2
      
      - name: Copy build project
        shell: cmd
        run: |
          copy "Code Patches\USBPcap.vcxproj" "usbpcap\USBPcapDriver\USBPcap.vcxproj"

      - name: Build USBPcap
        shell: cmd
        run: |
          msbuild "usbpcap\USBPcapDriver\USBPcap.vcxproj" /p:Configuration=Release /p:Platform=ARM64 /m /v:minimal

      - name: Upload result
        uses: actions/upload-artifact@v4
        with:
          name: usbpcap-arm64
          path: usbpcap/USBPcapDriver/bin/ARM64/Release/**
